#!/bin/bash
#/usr/lib/check_mk_agent/local
export LANG=de_DE.UTF-8

function confline # get first line from file $1 mathing $2, stripped of # and ; comment lines, stripped spaces and tabs down to spaces, remove trailing ;
{
 echo $(cat $1|grep -v '^$\|^\s*\#'|sed -e "s/[[:space:]]\+/ /g"|sed s/^\ //|sed s/\;//|grep -i "$2"|head -n 1)
}

function ati # ipv4 to longint
{
 ip4=$1; ipno=0
 for (( i=0 ; i<4 ; ++i )); do
   ((ipno+=${ip4%%.*}*$((254**$((3-${i})))))) # .0 .255 should not be counted
   ip4=${ip4#*.}
  done
 echo $ipno
}



## Drivespace
mountswatch='/home/adorfer /mnt /tmp'
warnpercentfree=10 # Prozent
alarmpercentfree=5 # Prozent
freewarn=$(( 100 - $warnpercentfree ))
freealarm=$(( 100 - $alarmpercentfree ))

for mountwatch in $mountswatch; do
  pathf=$(df $mountwatch|tail -1|tr -s " ")
  if [ ${#pathf} -ge 5 ]; then
    mountclearname=$(echo $mountwatch|tr / -)
    mount=$(echo $pathf|cut -d ' ' -f1)
    bsize=$(echo $pathf|cut -d ' ' -f2)
    bused=$(echo $pathf|cut -d ' ' -f3)
    dfree=$(echo $pathf|cut -d ' ' -f4)
    pfree=$(echo $pathf|cut -d ' ' -f5|tr -d %)
    echo "P Mountfree$mountclearname pfree=$pfree.0;$warnpercentfree:100;$alarmpercentfree:100|used=$bused.0;0:$bsize;0:$bsize|size=$bsize mount=$mount"
   fi;
 done
