#!/bin/bash
#/usr/lib/check_mk_agent/local
export LANG=de_DE.UTF-8

# do not execute backup files (~ extension)
 [ "$(echo ${BASH_SOURCE[0]}|awk '{print substr($0,length($0))}')" == "~" ] && exit 99

snstatusdir="/etc/supernode"

snstatusfiles="chklocalstatus.txt cmk_role_status.txt cmk_supernode_exit_status.txt cmk_supernode_status.txt"

for snstatusfile in ${snstatusfiles}; do
  filefull=${snstatusdir}/${snstatusfile}
  [ -f ${filefull} ] && cat ${filefull}
 done
