#!/bin/bash
#/usr/lib/check_mk_agent/local
export LANG=de_DE.UTF-8

# do not execute backup files (~ extension)
   [ "$(echo ${BASH_SOURCE[0]}|awk '{print substr($0,length($0))}')" == "~" ] && exit 99

## moved to /opt/sn_domaenen_controller/cmk-sn-exit-check.sh

